window.portfolioTranslations = window.portfolioTranslations || {};

window.portfolioTranslations.en = {
    siteTitle: "Zumar Portfolio",
    brand: "Zumar Portfolio",
    menu: "Menu",
    navHome: "Home",
    navAbout: "About",
    navSkills: "Skills",
    navProjects: "Projects",
    navExperience: "Experience",
    navCertificates: "Certificates",
    navContact: "Contact",
    heroEyebrow: "Hello, I am",
    heroTagline: "Digital Builder & Problem Solver",
    heroPrimaryBtn: "View Projects",
    heroSecondaryBtn: "Contact Me",
    heroCardTitle: "Current Focus",
    heroCardText: "Building digital products that are fast, functional, and user-experience driven.",
    aboutTitle: "About Me",
    aboutText:
      "I am a digital creator focused on modern web development and technology-driven problem solving. I enjoy turning ideas into clean, responsive, and impactful digital experiences.",
    skillsTitle: "Skills",
    skillCodingTitle: "Coding",
    skillCodingText: "Modern interface development, web performance, and structured front-end architecture.",
    skillDesignTitle: "Graphic Design",
    skillDesignText: "Visual branding, interface design, and creative assets with strong detail and consistency.",
    skillHardwareTitle: "Hardware & Software",
    skillHardwareText: "System setup, troubleshooting, device optimization, and digital tool integration.",
    projectsTitle: "Projects",
    projectImagePlaceholder: "Project Preview",
    project1Title: "Company Profile Website",
    project1Text: "A fast, SEO-friendly company profile site built to strengthen brand credibility.",
    project1Detail:
      "This project focused on company content architecture, technical SEO, loading speed, and responsive layouts for all screen sizes.",
    project2Title: "Analytics Dashboard",
    project2Text: "Interactive dashboard for real-time data visualization with a clean and intuitive layout.",
    project2Detail:
      "The dashboard includes KPI summaries, interactive charts, and data filters so teams can make faster data-driven decisions.",
    project3Title: "Product Landing Page",
    project3Text: "Responsive marketing page with smooth animations and strong call-to-action flow.",
    project3Detail:
      "The landing page uses a clear conversion funnel, persuasive copy, and performance optimization to improve campaign effectiveness.",
    projectBtn: "More Details",
    experienceTitle: "Experience",
    exp1Year: "2025 - Present",
    exp1Title: "Front-End Developer (Freelance)",
    exp1Text: "Built client websites from research and design to production-ready implementation.",
    exp1Proof: "Front-end work evidence (display max 640 x 360, no crop).",
    exp2Year: "2023 - 2025",
    exp2Title: "UI/UX & Visual Designer",
    exp2Text: "Designed digital product interfaces with a modern, user-centered approach.",
    exp2Proof: "UI/UX design evidence (display max 640 x 360, no crop).",
    exp3Year: "2021 - 2023",
    exp3Title: "IT Support & System Setup",
    exp3Text: "Handled installation, troubleshooting, and maintenance for hardware and software.",
    exp3Proof: "System setup evidence (display max 640 x 360, no crop).",
    certificatesTitle: "Certificates",
    cert1: "Front-End Development Certificate",
    cert2: "UI/UX Design Certificate",
    cert3: "IT Support Professional Certificate",
    contactTitle: "Contact",
    contactSubtitle: "Let us collaborate. Send your message through the form below.",
    contactEmailLabel: "Email:",
    contactWhatsappLabel: "WhatsApp:",
    contactSocialLabel: "Social:",
    contactNameLabel: "Name",
    contactEmailInputLabel: "Email",
    contactMessageLabel: "Message",
    contactNamePlaceholder: "Your name",
    contactEmailPlaceholder: "email@example.com",
    contactMessagePlaceholder: "Write your message...",
    contactSubmit: "Send Message",
    themeToggleLight: "Enable Dark Mode",
    themeToggleDark: "Enable Light Mode",
    modalClose: "Close",
    footerText: `© ${new Date().getFullYear()} Zumar Portfolio. All rights reserved.`
};
