window.portfolioTranslations = window.portfolioTranslations || {};

window.portfolioTranslations.id = {
    siteTitle: "Zumar Portfolio",
    brand: "Zumar Portfolio",
    menu: "Menu",
    navHome: "Beranda",
    navAbout: "Tentang",
    navSkills: "Keahlian",
    navProjects: "Proyek",
    navExperience: "Pengalaman",
    navCertificates: "Sertifikat",
    navContact: "Kontak",
    heroEyebrow: "Halo, Perkenalkan saya",
    heroTagline: "Di balik ketenanganku, ada pikiran yang selalu bekerja. Aku percaya bahwa kekuatan terbesar tidak selalu datang dari suara yang paling keras, tapi dari pengamatan yang tajam dan keputusan yang tepat.",
    heroPrimaryBtn: "Lihat Pengalaman Saya",
    heroSecondaryBtn: "Hubungi Saya",
    heroCardTitle: "Fokus Saat Ini",
    heroCardText: "Fokusku hari ini adalah investasi masa depanku. Langkahku tertuju pada Al-Azhar, hatiku terpaku pada Kalam-Nya, dan pengabdianku kusiapkan sepenuhnya untuk Ibu Pertiwi. Tidak ada waktu yang terbuang, hanya persiapan yang matang.",
    aboutTitle: "Tentang Saya",
    aboutText:
      "Saya adalah kreator digital yang berfokus pada pengembangan web modern dan pemecahan masalah berbasis teknologi. Saya senang mengubah ide menjadi pengalaman digital yang rapi, responsif, dan berdampak.",
    skillsTitle: "Keahlian",
    skillCodingTitle: "Profesional Dalam Berorganisasi",
    skillCodingText: "Berdedikasi di Departemen Pendidikan untuk membangun kapasitas intelektual, saya terbiasa memimpin sebagai Ketua Pelaksana yang mengedepankan sinergi. Namun, bagi saya, kesuksesan organisasi adalah prioritas utama—itulah mengapa saya tidak ragu menjadi kekuatan di balik layar bagi departemen lain demi memastikan setiap agenda mencapai tujuannya.",
    skillDesignTitle: "Graphic Design",
    skillDesignText: "Menggabungkan kreativitas visual dengan ketajaman organisasi. Sebagai desainer, saya tidak hanya menyusun piksel, tapi membangun narasi. Fokus saya adalah menciptakan desain yang edukatif, fungsional, dan mampu menjadi solusi komunikasi bagi setiap program yang saya kawal.",
    skillHardwareTitle: "Hardware & Software",
    skillHardwareText: "Bagi saya, teknologi adalah kesatuan antara estetika dan logika. Saya tidak hanya merancang tampilan (Software/Design), tetapi juga memahami bagaimana sistem bekerja dari akarnya (Hardware). Keahlian saya adalah memastikan bahwa setiap solusi digital yang saya buat memiliki fondasi teknis yang kokoh dan performa yang optimal.",
    projectsTitle: "Proyek",
    projectImagePlaceholder: "Preview Proyek",
    project1Title: "Website Company Profile",
    project1Text: "Situs profil perusahaan yang cepat, SEO-friendly, dan dirancang untuk meningkatkan kredibilitas brand.",
    project1Detail:
      "Proyek ini berfokus pada struktur konten perusahaan, optimasi SEO teknis, kecepatan loading, dan desain responsif untuk semua ukuran layar.",
    project2Title: "Dashboard Analytics",
    project2Text: "Dashboard interaktif untuk visualisasi data real-time dengan tampilan bersih dan intuitif.",
    project2Detail:
      "Dashboard ini menampilkan ringkasan KPI, grafik interaktif, serta filter data agar tim bisa mengambil keputusan lebih cepat berbasis data.",
    project3Title: "Landing Page Produk",
    project3Text: "Halaman pemasaran responsif dengan animasi halus dan call-to-action yang kuat.",
    project3Detail:
      "Landing page dibuat dengan struktur funnel yang jelas, copy yang fokus konversi, dan optimasi performa agar kampanye marketing lebih efektif.",
    projectBtn: "Lebih Detail",
    experienceTitle: "Pengalaman",
    exp1Year: "2025 - Sekarang",
    exp1Title: "Front-End Developer (Freelance)",
    exp1Text: "Mengerjakan website klien dari riset, desain, hingga implementasi production-ready.",
    exp2Year: "2023 - 2025",
    exp2Title: "UI/UX & Visual Designer",
    exp2Text: "Mendesain antarmuka produk digital dengan pendekatan user-centric dan modern.",
    exp3Year: "2021 - 2023",
    exp3Title: "IT Support & System Setup",
    exp3Text: "Menangani instalasi, troubleshooting, dan pemeliharaan hardware maupun software.",
    certificatesTitle: "Sertifikat",
    cert1: "Sertifikat Front-End Development",
    cert2: "Sertifikat UI/UX Design",
    cert3: "Sertifikat IT Support Professional",
    contactTitle: "Kontak",
    contactSubtitle: "Mari kolaborasi. Kirim pesan melalui form berikut.",
    contactEmailLabel: "Email:",
    contactWhatsappLabel: "WhatsApp:",
    contactSocialLabel: "Sosial:",
    contactNameLabel: "Nama",
    contactEmailInputLabel: "Email",
    contactMessageLabel: "Pesan",
    contactNamePlaceholder: "Nama Anda",
    contactEmailPlaceholder: "email@contoh.com",
    contactMessagePlaceholder: "Tulis pesan Anda...",
    contactSubmit: "Kirim Pesan",
    themeToggleLight: "Aktifkan Mode Gelap",
    themeToggleDark: "Aktifkan Mode Terang",
    modalClose: "Tutup",
    footerText: `© ${new Date().getFullYear()} Zumar Portfolio. All rights reserved.`
};
