window.portfolioTranslations = window.portfolioTranslations || {};

window.portfolioTranslations.ar = {
    siteTitle: "ملف زومار",
    brand: "ملف زومار",
    menu: "القائمة",
    navHome: "الرئيسية",
    navAbout: "نبذة",
    navSkills: "المهارات",
    navProjects: "المشاريع",
    navExperience: "الخبرات",
    navCertificates: "الشهادات",
    navContact: "التواصل",
    heroEyebrow: "مرحبًا، أنا",
    heroTagline: "باني رقمي وحلال المشكلات",
    heroPrimaryBtn: "عرض المشاريع",
    heroSecondaryBtn: "تواصل معي",
    heroCardTitle: "التركيز الحالي",
    heroCardText: "أبني منتجات رقمية سريعة وعملية وتركز على تجربة المستخدم.",
    aboutTitle: "نبذة عني",
    aboutText:
      "أنا صانع رقمي أركز على تطوير الويب الحديث وحل المشكلات بالتقنية. أستمتع بتحويل الأفكار إلى تجارب رقمية أنيقة ومتجاوبة وذات أثر.",
    skillsTitle: "المهارات",
    skillCodingTitle: "البرمجة",
    skillCodingText: "تطوير واجهات حديثة، تحسين أداء الويب، وبناء هيكلية Front-End منظمة.",
    skillDesignTitle: "التصميم الجرافيكي",
    skillDesignText: "الهوية البصرية، تصميم الواجهات، وإنتاج مواد إبداعية بدقة واتساق.",
    skillHardwareTitle: "الأجهزة والبرمجيات",
    skillHardwareText: "إعداد الأنظمة، معالجة الأعطال، تحسين الأجهزة، ودمج الأدوات الرقمية.",
    projectsTitle: "المشاريع",
    projectImagePlaceholder: "معاينة المشروع",
    project1Title: "موقع تعريفي للشركات",
    project1Text: "موقع سريع وصديق لمحركات البحث يعزز مصداقية العلامة التجارية.",
    project1Detail:
      "يركز هذا المشروع على هيكلة محتوى الشركة، تحسين SEO التقني، سرعة التحميل، وتصميم متجاوب لكل أحجام الشاشات.",
    project2Title: "لوحة تحليلات",
    project2Text: "لوحة تفاعلية لعرض البيانات الفورية بتجربة نظيفة وسهلة الاستخدام.",
    project2Detail:
      "تشمل اللوحة ملخصات KPI ورسومًا تفاعلية وفلاتر بيانات لمساعدة الفرق على اتخاذ قرارات أسرع.",
    project3Title: "صفحة هبوط لمنتج",
    project3Text: "صفحة تسويقية متجاوبة مع حركات سلسة ودعوات إجراء فعالة.",
    project3Detail:
      "تم بناء صفحة الهبوط بفنل تحويل واضح، نص تسويقي مركز، وتحسين أداء لتعزيز نتائج الحملات.",
    projectBtn: "مزيد من التفاصيل",
    experienceTitle: "الخبرات",
    exp1Year: "2025 - الآن",
    exp1Title: "مطوّر واجهات أمامية (مستقل)",
    exp1Text: "نفذت مواقع العملاء من البحث والتصميم حتى الإطلاق الجاهز للإنتاج.",
    exp1Proof: "دليل أعمال الواجهة الأمامية (عرض أقصى 640 × 360 دون قص).",
    exp2Year: "2023 - 2025",
    exp2Title: "مصمم واجهات وتجربة مستخدم",
    exp2Text: "صممت واجهات منتجات رقمية بنهج حديث يركز على المستخدم.",
    exp2Proof: "دليل أعمال UI/UX (عرض أقصى 640 × 360 دون قص).",
    exp3Year: "2021 - 2023",
    exp3Title: "دعم تقني وإعداد أنظمة",
    exp3Text: "أدرت التثبيت والصيانة وحل المشكلات للأجهزة والبرمجيات.",
    exp3Proof: "دليل إعداد الأنظمة (عرض أقصى 640 × 360 دون قص).",
    certificatesTitle: "الشهادات",
    cert1: "شهادة تطوير الواجهات الأمامية",
    cert2: "شهادة تصميم UI/UX",
    cert3: "شهادة محترف الدعم التقني",
    contactTitle: "التواصل",
    contactSubtitle: "لنبدأ تعاونًا. أرسل رسالتك عبر النموذج التالي.",
    contactEmailLabel: "البريد الإلكتروني:",
    contactWhatsappLabel: "واتساب:",
    contactSocialLabel: "المنصات:",
    contactNameLabel: "الاسم",
    contactEmailInputLabel: "البريد الإلكتروني",
    contactMessageLabel: "الرسالة",
    contactNamePlaceholder: "اسمك",
    contactEmailPlaceholder: "email@example.com",
    contactMessagePlaceholder: "اكتب رسالتك...",
    contactSubmit: "إرسال الرسالة",
    themeToggleLight: "تفعيل الوضع الداكن",
    themeToggleDark: "تفعيل الوضع الفاتح",
    modalClose: "إغلاق",
    footerText: `© ${new Date().getFullYear()} ملف زومار. جميع الحقوق محفوظة.`
};
